# 이미지
FROM        lanark/zamsee-base:latest
# 유저
MAINTAINER  dfg1499@gmail.com
# 언어 환경 설정
ENV         LANG C.UTF-8
ENV         DJANGO_SETTINGS_MODULE config.settings.local

# 현재 폴더 전체를 /srv/app에 복사
COPY        . /srv/app
# requirememts 설치
RUN         /root/.pyenv/versions/app/bin/pip install -r \
            /srv/app/requirements.txt

#pyenv 환경 설정
WORKDIR     /srv/app
RUN         pyenv local app

#Nginx

