# Generated by Django 2.0.2 on 2018-03-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zsuser',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='zsuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
